/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author boyst
 */
public class Entering_teams extends javax.swing.JFrame {

    /**
     * Creates new form Entering_teams
     */
    private final int teams = 10;
    static int counter;
    
//    ArrayList<Teams> list = new ArrayList<>();
    Teams list[] = new Teams[teams];
    Teams check_list[] = new Teams[teams];
    public Entering_teams() {
        initComponents();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TitleLabel = new javax.swing.JLabel();
        NameLabel = new javax.swing.JLabel();
        IDLabel = new javax.swing.JLabel();
        NameTextField = new javax.swing.JTextField();
        IDTextField = new javax.swing.JTextField();
        AddButton = new javax.swing.JButton();
        SortButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TeamsTable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ABS System");

        TitleLabel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        TitleLabel.setText("ABS System");

        NameLabel.setText("Team Name");

        IDLabel.setText("Team ID");

        AddButton.setText("ADD");
        AddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddButtonActionPerformed(evt);
            }
        });

        SortButton.setText("SORT");
        SortButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SortButtonActionPerformed(evt);
            }
        });

        TeamsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rank", "Team ID", "Team Name", "Solved Questions", "Elapsed Time"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(TeamsTable);
        if (TeamsTable.getColumnModel().getColumnCount() > 0) {
            TeamsTable.getColumnModel().getColumn(0).setResizable(false);
            TeamsTable.getColumnModel().getColumn(0).setPreferredWidth(40);
            TeamsTable.getColumnModel().getColumn(1).setResizable(false);
            TeamsTable.getColumnModel().getColumn(1).setPreferredWidth(45);
            TeamsTable.getColumnModel().getColumn(2).setResizable(false);
            TeamsTable.getColumnModel().getColumn(3).setResizable(false);
            TeamsTable.getColumnModel().getColumn(3).setPreferredWidth(90);
            TeamsTable.getColumnModel().getColumn(4).setResizable(false);
            TeamsTable.getColumnModel().getColumn(4).setPreferredWidth(80);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(IDLabel)
                                    .addComponent(NameLabel))
                                .addGap(34, 34, 34)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(IDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(SortButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 394, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(250, 250, 250)
                        .addComponent(TitleLabel)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(NameLabel)
                            .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(IDTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IDLabel))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AddButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(SortButton, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(TitleLabel)
                        .addGap(22, 22, 22)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void AddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddButtonActionPerformed
        // TODO add your handling code here:
        String name;int id;boolean flag=true;
        DefaultTableModel model = (DefaultTableModel) TeamsTable.getModel();
        name = NameTextField.getText();
        if(name.equals("")){
            JOptionPane.showMessageDialog(null, "please enter team's name","Error",JOptionPane.ERROR_MESSAGE);
        }else{
            try{
                id = Integer.parseInt(IDTextField.getText());
                if(counter>0){
                    for(int i=0;i<counter;i++){
                        if(list[i].getTeam_name().equalsIgnoreCase(name) || list[i].getTeam_id() == id){
                            JOptionPane.showMessageDialog(null, "don't repeat team's name or id","Error",JOptionPane.ERROR_MESSAGE);
                            flag=false;
                            break;
                        }
                    }
                }if(flag){
                list[counter] = new Teams(name, id);
                model.addRow(new Object[]{counter+1+"",list[counter].getTeam_id()+"",list[counter].getTeam_name(),
                                            list[counter].getSolved_questions()+"/10",list[counter].getElapsed_time()+""});
                counter++;
                }
            }catch(NullPointerException e){
                JOptionPane.showMessageDialog(null, "There is no teams entered","Error",JOptionPane.ERROR_MESSAGE);
            }catch(NumberFormatException e){
                JOptionPane.showMessageDialog(null, "Please enter numbers only in id's text field","Error",JOptionPane.ERROR_MESSAGE);
            }catch(ArrayIndexOutOfBoundsException e){
                JOptionPane.showMessageDialog(null, "can't add more than " + teams + " Teams","Error",JOptionPane.ERROR_MESSAGE);
            }catch(Exception e){
                JOptionPane.showMessageDialog(this, e);
            }
        }
        NameTextField.setText("");
        IDTextField.setText("");
    }//GEN-LAST:event_AddButtonActionPerformed

    private void SortButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SortButtonActionPerformed
        // TODO add your handling code here:
        try{
            for(int i=0;i<teams;i++){
                for(int j=i+1;j<teams;j++){
                    if(list[i].getSolved_questions()<list[j].getSolved_questions()){
                        Teams temp = list[i];
                        list[i]=list[j];
                        list[j]=temp;
                    }
                    else if(list[i].getSolved_questions()==list[j].getSolved_questions()){
                        if(list[i].getElapsed_time()>list[j].getElapsed_time()){
                            Teams temp = list[i];
                            list[i]=list[j];
                            list[j]=temp;
                        }
                    }
                }
            }
            DefaultTableModel model = (DefaultTableModel) TeamsTable.getModel();
            model.getDataVector().removeAllElements();
            model.fireTableDataChanged();
            for(int i=0;i<teams;i++){
                model.addRow(new Object[]{i+1+"",list[i].getTeam_id()+"",list[i].getTeam_name(),
                                            list[i].getSolved_questions()+"/10",list[i].getElapsed_time()+""});
            }
        }catch(NullPointerException e){
            JOptionPane.showMessageDialog(null, "Please enter the 10 teams","Error",JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_SortButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Entering_teams.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Entering_teams.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Entering_teams.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Entering_teams.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Entering_teams().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddButton;
    private javax.swing.JLabel IDLabel;
    private javax.swing.JTextField IDTextField;
    private javax.swing.JLabel NameLabel;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JButton SortButton;
    private javax.swing.JTable TeamsTable;
    private javax.swing.JLabel TitleLabel;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
